name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "dev", "master" ]
  workflow_dispatch:

jobs:
  lint_and_check:
    name: Lint & Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv pip install --system -e .[dev]

      - name: Lint with ruff
        run: uv run ruff check src tests

      - name: Check formatting with ruff
        run: uv run ruff format --check src tests

      - name: Check formatting with black
        run: uv run black --check src tests

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv pip install --system -e .[dev]

      - name: Run mypy
        run: uv run mypy src

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv pip install --system -e .[dev]

      - name: Run pytest
        run: uv run pytest
