name: Publish to TestPyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # This step is no longer needed
      # - name: Install build tool
      #   run: pip install build

      # This step is no longer needed. The publish action will do it.
      # - name: Build package
      #   run: python -m build

      # This single action will now handle both building and publishing
      - name: Build and publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/