name: Publish to TestPyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/master'
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check file encoding
        run: file pyproject.toml

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # This step is optional but good practice
      - name: Install build tool
        run: pip install build

      # This step no longer needs `uv add...` or `uv run`.
      # It will use the `build` command we just installed.
      - name: Build package
        run: python -m build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/