name: Publish to TestPyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
#    if: |
#      github.event.workflow_run.conclusion == 'success' &&
#      github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup venv
        run: uv venv

      - name : Activate venv
        run: source .venv/bin/activate

      - name: Install build tool
        run: uv pip install hatchling twine

      - name: Build package
        run: hatchling build

      - name: Build and publish package to TestPyPI
        run: twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}